@tkey = your_trello_api_key

# Go to https://trello.com/1/authorize?expiration=1day&name=MyPersonalToken&scope=read&response_type=token&key={{tkey}}
@ttoken = your_trello_api_token
@tbase = https://api.trello.com/1

@dbase = https://doerfler.io:8042

@u = your_user
@g = your_slug
@refresh = {{dbase}}/goal/{{g}}/refresh?username={{u}}

### Get trello boards
# @name getBoards
GET {{tbase}}/members/me/boards?key={{tkey}}&token={{ttoken}}

### Now we got the id of the relevant board
@boardId = {{getBoards.response.body.$[?(@.name=='your_board_name')].id}}

# @name createHook
POST {{tbase}}/tokens/{{ttoken}}/webhooks/?key={{tkey}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

description=refresh graph
&callbackURL={{refresh}}
&idModel={{boardId}}

###

@hookId = {{createHook.response.body.$.id}}

### This gave us a hook
# which we can look at
GET {{tbase}}/tokens/{{ttoken}}/webhooks/{{hookId}}?key={{tkey}} HTTP/1.1

### and finally delete again
DELETE {{tbase}}/tokens/{{ttoken}}/webhooks/{{hookId}}?key={{tkey}} HTTP/1.1

### List all webhooks just to make sure we got them all
GET {{tbase}}/tokens/{{ttoken}}/webhooks/?key={{tkey}} HTTP/1.1